import type { SourceRecord } from '../sources/types';

/**
 * The full ~11-feed preset list from DESIGN.md §2, seeded into the `Sources`
 * table (Phase 2). Editable afterwards via the table itself — this is only
 * the initial data.
 */
export const FULL_SOURCE_PRESETS: SourceRecord[] = [
  {
    sourceId: 'hn',
    name: 'Hacker News',
    rssUrl: 'https://hnrss.org/frontpage',
    siteUrl: 'https://news.ycombinator.com',
    defaultTopic: 'dev',
    topics: ['dev'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'verge',
    name: 'The Verge',
    rssUrl: 'https://www.theverge.com/rss/index.xml',
    siteUrl: 'https://www.theverge.com',
    defaultTopic: 'gadgets',
    topics: ['gadgets'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'arstechnica',
    name: 'Ars Technica',
    rssUrl: 'https://feeds.arstechnica.com/arstechnica/index',
    siteUrl: 'https://arstechnica.com',
    defaultTopic: 'gadgets',
    topics: ['gadgets', 'dev'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'techcrunch',
    name: 'TechCrunch',
    rssUrl: 'https://techcrunch.com/feed/',
    siteUrl: 'https://techcrunch.com',
    defaultTopic: 'startups',
    topics: ['startups'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'sciencedaily',
    name: 'ScienceDaily',
    rssUrl: 'https://www.sciencedaily.com/rss/top/technology.xml',
    siteUrl: 'https://www.sciencedaily.com',
    defaultTopic: 'science',
    topics: ['science'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'physorg',
    name: 'Phys.org',
    rssUrl: 'https://phys.org/rss-feed/',
    siteUrl: 'https://phys.org',
    defaultTopic: 'science',
    topics: ['science'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'quanta',
    name: 'Quanta Magazine',
    rssUrl: 'https://www.quantamagazine.org/feed/',
    siteUrl: 'https://www.quantamagazine.org',
    defaultTopic: 'science',
    topics: ['science'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'nature',
    name: 'Nature News',
    rssUrl: 'https://www.nature.com/nature.rss',
    siteUrl: 'https://www.nature.com',
    defaultTopic: 'science',
    topics: ['science', 'bio'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'arxiv-ai',
    name: 'arXiv cs.AI',
    rssUrl: 'https://rss.arxiv.org/rss/cs.AI',
    siteUrl: 'https://arxiv.org/list/cs.AI/recent',
    defaultTopic: 'ai',
    topics: ['ai'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'github-blog',
    name: 'GitHub Blog',
    rssUrl: 'https://github.blog/feed/',
    siteUrl: 'https://github.blog',
    defaultTopic: 'dev',
    topics: ['dev'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
  {
    sourceId: 'huggingface-blog',
    name: 'Hugging Face Blog',
    rssUrl: 'https://huggingface.co/blog/feed.xml',
    siteUrl: 'https://huggingface.co/blog',
    defaultTopic: 'ai',
    topics: ['ai'],
    weight: 1,
    enabled: true,
    failCount: 0,
  },
];
